theme: jekyll-theme-hacker
title: [Jeffrey Winn's Blog]
description: [Assorted thoughts and information of nominal value]
show_downloads: false
toc:
  on: true
favicon: /docs/favicon.ico
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
gems:
    - searchyll
elasticsearch:
  url: https://z9gvt4xaec:czbzpum2h8@github-2719164518.us-west-2.bonsaisearch.net:443
  index_name: github